version: "3"
services:
  kong:
    image: kong:alpine
    environment:
      KONG_DATABASE: "off"
      KONG_DNS_RESOLVER: "127.0.0.11"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    volumes:
      - ./kong:/usr/local/kong/declarative
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      PGADMIN_CONFIG_SERVER_MODE: "False"
  keycloak:
    build: ./keycloak
    depends_on:
      - postgres
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /tmp/tindeer-realm.json
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - 8080:8080
  pgadmin:
    build: ./pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: keycloak@tindeer.com
      PGADMIN_DEFAULT_PASSWORD: keycloak
    ports:
      - 5050:80
    depends_on:
      - postgres  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  profile:
    image: 'docker.io/tindeer/brinder-profile-api:latest'
    ports:
      - 9080:8080
    environment:
      spring_profiles_active: security,docker
      keycloak_credentials_secret: 327c1a4c-10de-4508-b8ab-6d6fdaef489d
    depends_on:
      - mongo
      - keycloak
  match:
    image: 'docker.io/tindeer/brinder-match-api:latest'
    ports:
      - 9081:8080
    environment:
      spring_profiles_active: security,docker
      keycloak_credentials_secret: 327c1a4c-10de-4508-b8ab-6d6fdaef489d
    depends_on:
      - mongo
      - keycloak
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /doc/tindeer.yaml
      DEEP_LINKING: "true"
      OAUTH2_REDIRECT_URL: http://localhost:8888/oauth2-redirect.html
      OAUTH_CLIENT_ID: swagger
      OAUTH_USE_PKCE: "true"  
      OAUTH_REALM: tindeer
      OAUTH_APP_NAME: swagger
    ports: 
      - 8888:8080
    volumes:
      - ./swagger:/doc